# Generated by Django 4.1.7 on 2023-03-30 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('0bcd75a6-84c9-4fb9-a061-d97427340f8f'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('0bcd75a6-84c9-4fb9-a061-d97427340f8f'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('country', models.CharField(max_length=50)),
                ('userDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.userdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
