# Generated by Django 4.1.7 on 2023-03-30 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f6c1ee6c-4c9e-4e3f-b655-79681506bbcf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f6c1ee6c-4c9e-4e3f-b655-79681506bbcf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
