# Generated by Django 4.1.7 on 2023-03-30 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0005_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bb9cefa0-4950-4e12-aee9-9e7219a85704'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bb9cefa0-4950-4e12-aee9-9e7219a85704'), editable=False, primary_key=True, serialize=False),
        ),
    ]
