# Generated by Django 4.1.7 on 2023-03-30 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0009_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b97c63ec-4383-41e5-82b5-18acfc9e71b4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b97c63ec-4383-41e5-82b5-18acfc9e71b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
