# Generated by Django 4.1.7 on 2023-03-30 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0012_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1298f7dc-4dde-4c82-86ef-06a03aa565f9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1298f7dc-4dde-4c82-86ef-06a03aa565f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
