# Generated by Django 4.1.7 on 2023-03-31 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0015_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('98204c9e-0fc0-43c7-9e15-8710da3d635c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8241b59e-5f4e-47e3-a4ba-72e1582aa56b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
