# Generated by Django 4.1.7 on 2023-03-31 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0016_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('306379dc-f2d2-46de-b982-3348a3596c8b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3889d3ef-a267-4610-aa67-7edbe1bf58c0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
