# Generated by Django 4.1.7 on 2023-03-31 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0017_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3aec872f-2883-4741-aee9-976b529c318e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bd082df1-a5a5-4780-ad64-3bc790d6143a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
