# Generated by Django 4.1.7 on 2023-03-31 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0018_alter_useraddress_uid_alter_userdetails_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='uid',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7e83df8-5605-41cb-8729-65a0fac702dd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c6608829-9ac4-442c-87da-a857f12cf99a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
