# Generated by Django 4.1.7 on 2023-03-31 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0019_remove_useraddress_uid_useraddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('630b6d69-b2e1-4012-8342-88d4bf19161d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3c668ec2-bc17-41e5-a11f-00cc1db315d4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
